# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eab6d0bbeef94467042cba4e1d468cc30ab1e320fd42afe8153a02de08692b67b14f70f86f6951c882167622edd4a01341cb7b0927108e0b33132acc22911bb

test:
  secret_key_base: 72660180984bd1d42db9bff05fb64c7cd6f0d6ef061833f872af0e90a1a4b858fbe094cd32d48510ca61461e7ce79c519b7dada08f02e28dbfd0860bda0de131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
